language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm ci
  - CI=false npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: 830ef2572b99df8dd05abd212a7995d8018235b1
    local_dir: build
    on:
      branch: master