language: node_js

node_js:
  - "stable"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

before_script:
  - npm ci
  - CI=false npm run build --base-href /api-post-task/
  - mv build/api-post-task/index.html build/api-post-task/404.html

deploy:
  - provider: pages:git
    skip_cleanup: true
    deploy_key: 5778f6a4edea3e07ec2d7bb91af58d1fcc230d41
    local_dir: build/api-post-task
    keep_history: true
    edge: true
    target_branch: gh-pages
    on:
      branch: master
      repo: Scherlock90/api-post-task