language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - npm ci
  - CI=false npm run build

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: 5778f6a4edea3e07ec2d7bb91af58d1fcc230d41
    github_token: 5778f6a4edea3e07ec2d7bb91af58d1fcc230d41
    local_dir: build
    on:
      branch: master
      tags: false