language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - npm ci
  - CI=false npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    deploy_key: $5778f6a4edea3e07ec2d7bb91af58d1fcc230d41
    local_dir: build
    keep_history: true
    edge: true
    on:
      branch: master