language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - npm ci
  - CI=false npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: b2772329eaeb48267d381da972841033c7c9c074
    local_dir: build
    keep_history: true
    on:
      branch: master